services:
  db-dolomite:
    build: .
    container_name: db-dolomite
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo db:${DB_PORT}/${DB_NAME} --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks: 
      - net-dolomite
    # volumes:
      # - ./data/db:/data/db
      #- ./scripts:/docker-entrypoint-initdb.d
