services:
  db-dolomite:
    build: .
    container_name: db-dolomite
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks: 
      - net-dolomite
    volumes:
      - ./data/db:/data/db
